# Generated by Django 3.1.2 on 2022-04-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20220409_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
