# Generated by Django 3.1.2 on 2022-04-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_carrer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrer',
            new_name='Career',
        ),
    ]
