# Generated by Django 3.1.2 on 2022-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20220424_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='image',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='Job Application/'),
        ),
    ]
