# Generated by Django 3.1.2 on 2022-05-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20220427_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='image',
        ),
        migrations.AddField(
            model_name='career',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='Job Application/'),
        ),
    ]
