# Generated by Django 3.1.2 on 2022-05-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employeedetail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='image',
        ),
    ]
