# Generated by Django 3.1.2 on 2022-05-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_employeedetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='Employee Profile Picture/'),
        ),
    ]
