# Generated by Django 3.1.2 on 2022-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeedetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
