# Generated by Django 3.1.2 on 2022-05-27 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20220527_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='date',
            field=models.DateTimeField(default=datetime.time(18, 1, 18, 841674)),
        ),
    ]
