# Generated by Django 3.1.2 on 2022-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20220527_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
